/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface PrivateVaultInterface extends utils.Interface {
  functions: {
    "_query()": FunctionFragment;
    "_save(string)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "_query" | "_save"): FunctionFragment;

  encodeFunctionData(functionFragment: "_query", values?: undefined): string;
  encodeFunctionData(functionFragment: "_save", values: [string]): string;

  decodeFunctionResult(functionFragment: "_query", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_save", data: BytesLike): Result;

  events: {};
}

export interface PrivateVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PrivateVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _query(overrides?: CallOverrides): Promise<[string]>;

    _save(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _query(overrides?: CallOverrides): Promise<string>;

  _save(
    data: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _query(overrides?: CallOverrides): Promise<string>;

    _save(data: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    _query(overrides?: CallOverrides): Promise<BigNumber>;

    _save(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _query(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _save(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
